@IsTest
public class DetectLanguageClassTest {
    //test method to parse json data
    static testMethod void testDetectLanguageClass()
    {
        DetectLanguageClass dlc = new DetectLanguageClass();
        DetectLanguageClass.Data data = new DetectLanguageClass.Data();
        DetectLanguageClass.Detections detections = new DetectLanguageClass.Detections();
        System.assert(true);
    }   
}